### ISSUE TITLE
Readme is outdated

### ISSUE THREAD

**Issue by michielbdejong** [pondersource/nextcloud-mfa-awareness#11]
It seems we're all working off the `mrv/gss` branch now, right?
So maybe we can merge that branch into main and update the readme to describe the setup with Docker?
Or do we want to keep the old user_saml instructions until #10 is done?

**Comment by navid-dada** [comment]
`mrv/gss` is not in a valid state and merging it into the main cause that our main branch transforms to an unstable state.
so we have another branch `mrv/dockerfile-creation` that can be merged with the main. It contains our test case for checking `webauthen` and `totp` authentication methods.

**Comment by michielbdejong** [comment]
OK, let's merge that one -> #12
And then someone can start working on this issue, to update the readme.

**Comment by michielbdejong** [comment]
I'll do this after #7 and #10
