### ISSUE TITLE
Nextcloud GUI not visible from browser

### ISSUE THREAD

**Issue by michielbdejong** [pondersource/nextcloud-mfa-awareness#15]
This affects @navid-dada's dev setup. I'll try to reproduce the problem.

**Comment by navid-dada** [comment]
you can just run the gss docker-compose.
I noticed that the tester container has some HTTP/HTTPS/NO proxy in its env 
after it, I unset those proxies and check the apache2/access.log in the Nextcloud master node.

* when you curl the Nextcloud from the tester container it made some logs but it cannot load the login file.
* when you are browsing master from your local browser by localhost:8080 it can load the login page and there is a plant of logs on apache/access.log file
*  when you are trying to browse the master node using a headless browser  localhost:5800 there is no hit  on apache/access.log file

**Comment by michielbdejong** [comment]
OK, I'm testing this in `main`. Since the docker-compose.yml doesn't use a testnet, we need to browse to the container IPs. To find these, run:
```
docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' nextcloud
```
For instance:
```
export NEXTCLOUD=`docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' nextcloud`
curl http://$NEXTCLOUD
<!DOCTYPE html>
<html>
<head>
        <script> window.location.href="index.php"; </script>
        <meta http-equiv="refresh" content="0; URL=index.php">
</head>
</html>
```

**Comment by michielbdejong** [comment]
I do notice it has the port as "8080:80", that should probably be "80:80"?

**Comment by michielbdejong** [comment]
I did notice that the Firefox tester doesn't work when not using a testnet, apparently.

**Comment by michielbdejong** [comment]
I added a testnet in the php-version-8 branch and I can now see sunet-nc1 both on:
http://mesh.pondersource.org:8081/index.php
http://mesh.pondersource.org:5800 -> http://sunet-nc1/index.php

@navid-dada can you confirm if this is fixed for you in the php-version-8 branch?
