### ISSUE TITLE
Take our Check out of workflowengine app and put it into an app of our own?

### ISSUE THREAD

**Issue by michielbdejong** [pondersource/nextcloud-mfa-awareness#27]
After #26, we can clean up so that our code addition is done as a Nextcloud app (based on the MFA Checker app we already have), so that we don't have to change the https://github.com/nextcloud/server code

I think https://github.com/nextcloud/server/blob/master/apps/workflowengine/lib/Manager.php#L684 should allow this.

**Comment by michielbdejong** [comment]
And for the frontend part, something like: https://github.com/nextcloud/files_accesscontrol/blob/master/js/admin.js

**Comment by michielbdejong** [comment]
In https://github.com/nextcloud/server/blob/master/apps/workflowengine/lib/Manager.php#L673 you can see it loads built-in checks and registered checks.

**Comment by mrvahedi68** [comment]
Related PR: https://github.com/pondersource/server/pull/240

**Comment by mrvahedi68** [comment]
The failed actions related to my changes passed after merging Nextcloud to my branch. But some actions failed now for `phpUnit` and `Cypress`.  `phpUnit` failed because on action pipeline got an error when wanted to install `phpUnit` : `403: rate limit exceeded `. And for `Cypress` two tests failed for checking some colors and got a timeout. this section of the site is not related to any of my changes.

**Comment by mrvahedi68** [comment]
By some retries Actions about `phpUnit` passed and only remains `Cypress` failures.

**Comment by michielbdejong** [comment]
So what is the way forward?

**Comment by mrvahedi68** [comment]
We must run this actions locally to debug the progress and can see the Cypress screenshots from point of issue.

**Comment by michielbdejong** [comment]
Hm, as discussed in https://github.com/pondersource/server/pull/240#issuecomment-1367919484 I think we can probably just ignore this?

**Comment by michielbdejong** [comment]
@navid-dada can you elaborate on why you changed the title?

**Comment by michielbdejong** [comment]
Btw 'Check' in the issue title refers to `OCP\WorkflowEngine\ICheck`

**Comment by michielbdejong** [comment]
So which one will we add it to?
1. [mfachecker](https://github.com/pondersource/nextcloud-mfa-awareness/tree/main/mfachecker)
2. [MohammadReza's newly generated app](https://github.com/pondersource/mfa-verified-zone)
3. [the existing file_accesscontrol app](https://github.com/nextcloud/files_accesscontrol)

**Comment by michielbdejong** [comment]
For reference, in our current dev environment, we are adding the code straight into the workflow engine app: [apps/workflowengine/lib/Check/MfaVerified.php](https://github.com/pondersource/server/pull/240/files#diff-324119d2db6f3d5a6d7546558dd8011e16e04683d83c4d29d69ff5f250f353d1)

**Comment by michielbdejong** [comment]
As discussed with @navid-dada just now it seems there is no good way (yet) for a Nextcloud app to register a Check. So if that's the case then we can either leave our check where it is, or propose such a mechanism upstream? Should we discuss this with Nextcloud support?

**Comment by michielbdejong** [comment]
What happens if we just inject our Check into the `OCA\WorkflowEngine\Check` namespace? Will workflowengine not just be able to find it? How does it list them anyway?

**Comment by michielbdejong** [comment]
I think checks are loaded by https://github.com/nextcloud/server/blob/1daab5751d632e4d1dac60d28fed3b28af346b54/apps/workflowengine/composer/composer.json#L10 but I haven't found any registry of them yet, apart from that. Maybe they are just referred to by their class name?

**Comment by michielbdejong** [comment]
Ah yes, I think that's the case, look! https://github.com/nextcloud/server/blob/047acc32ad07de4bb481c267b9f730ce644efbd1/apps/workflowengine/lib/Migration/Version2000Date20190808074233.php#L59

**Comment by michielbdejong** [comment]
So we have 4 options:
1. leave things as they are
2. create a "config var has a certain value" check, and use that in our app
3. do everything in our app
4. leave our PR to the workflowengine code fully usable, and also create an app that uses the check in the correct way (to avoid misconfiguration by server admins)

**Comment by michielbdejong** [comment]
But we think the frontend edits would still be needed in nextcloud/server...

**Comment by michielbdejong** [comment]
We agree option 4 would be better than option 1

**Comment by michielbdejong** [comment]
Advantage of option 4: it's less difficult for us to implement
Advantage of option 2: it will be more useful at the work flow engine level, and we're not asking the server admin to use this check anyway, so it would be fine if it's a bit more low-level.

**Comment by michielbdejong** [comment]
Disadvantage of option 2: we would then probably also support other data types, etcetera, and it's not clear how useful it would be.

**Comment by michielbdejong** [comment]
Another disadvantage of option 2: in general, server admins don't have know knowledge session variable names and values

**Comment by michielbdejong** [comment]
So maybe I would prefer option 4 as my top choice.
@navid-dada what would your preference be?
@mrvahedi68 what do you think?

Let's try to take a decision about this.

**Comment by michielbdejong** [comment]
Great! So nothing left to do here then.
