### ISSUE TITLE
Create a Check for a specific folder path

### ISSUE THREAD

**Issue by michielbdejong** [pondersource/nextcloud-mfa-awareness#28]

**Comment by michielbdejong** [comment]
Maybe we can use the Request URL check?

**Comment by navid-dada** [comment]
I found that  using tags can be a better option, in NextCloud Tag has this two options: 
- visibility
- editable 
you can find them in the `oc_systemtag` table. 
so we can create a system tag that is invisible and unable to change and assign that tag to files and folders.
With this approach, we just need to add one `Check` to verify whether the user is logged in with MFA or not. and the rest of the work will be assigned to NextCloud infrastructure.

**Comment by navid-dada** [comment]
Also, there is another table `oc_systemtag_object_mapping` that indicates which object has which tag.

**Comment by mrvahedi68** [comment]
For selecting a path, the private tag is a good idea and we can find tagged folders from the database. And for limiting access we must change in `Workflow engine` and add a rule for `Mfa verified`. after these settings, we can limit access to tagged folders when someone does not have `Mfa Verified` by using of `File access control` app.

**Comment by mrvahedi68** [comment]
For this phase we can use `file access control` with new `Mfa Verified` check and a regex over the file name (File name contains or starts with something). For the next step we must create an app to automatically tag folders that selected by admin in the file system.

**Comment by michielbdejong** [comment]
Done
