### ISSUE TITLE
adjust tests for PR#668 on user_saml.

### ISSUE THREAD

**Issue by navid-dada** [pondersource/nextcloud-mfa-awareness#31]
https://github.com/nextcloud/user_saml/pull/668#issuecomment-1316721095

**Comment by michielbdejong** [comment]
@navid-dada Who is working on this?

**Comment by mrvahedi68** [comment]
Yes I'll check them. @navid-dada

**Comment by mrvahedi68** [comment]
Fixed at [This PR](https://github.com/pondersource/user_saml/pull/2).
