### ISSUE TITLE
Try out what happens if a folder is not owned by any user (e.g. shared S3 bucket / group drive)

### ISSUE THREAD

**Issue by michielbdejong** [pondersource/nextcloud-mfa-awareness#32]

**Comment by navid-dada** [comment]
Is there any feature for sharing files on NextCloud to share a file without any owner?

**Comment by michielbdejong** [comment]
I think the way to set up such a folder (not owned by any user) is with https://apps.nextcloud.com/apps/groupfolders
See also https://www.youtube.com/watch?v=LaTd-TTj41Q and https://help.nextcloud.com/t/how-to-create-a-group-folder/43740/2

**Comment by mrvahedi68** [comment]
I saw video and read the documents. I don't understand why this section is important. As you know only Admin and Owner can set or unset `MFA verified check`, so if this type of files has no owner then only Admin can change the `MFA verified check`. 
Admin creates this type of files and folders and The only verified user to change in the check is Admin.

**Comment by mrvahedi68** [comment]
Tested Scenario:
Installed `Group folder` app on nextcloud and created some group. Created new folder for this group. Users inside that group had access to that folder completely, then by admin added our restricted tag to the folder. after that only users with `Mfa verified` check had access to the folder. 
Another test scenario:
Created one folder with `Admin1` and added tag with `Admin2` and the result was same as first scenario.

**Comment by michielbdejong** [comment]
LGTM, great work!

**Comment by michielbdejong** [comment]
For completeness, this is another way to add a mounted storage for all users. I would expect the tag would apply in the same way for this configuration:

https://docs.nextcloud.com/server/latest/admin_manual/configuration_files/external_storage_configuration_gui.html#storage-configuration

**Comment by mrvahedi68** [comment]
I do that. Here is the result:
It was as expected. Test result here is from `user2` that has not MFA verified.

![11](https://user-images.githubusercontent.com/34796044/223035330-6a90c0f2-d22e-4449-b381-c5981107c62a.JPG)
![22](https://user-images.githubusercontent.com/34796044/223035332-2a4462eb-d5c3-499e-8b74-e5cca36b262a.JPG)
