### ISSUE TITLE
Look for a solution for the ‘recently used’ app

### ISSUE THREAD

**Issue by michielbdejong** [pondersource/nextcloud-mfa-awareness#33]

**Comment by navid-dada** [comment]
@michielbdejong  checked it and it was working correctly. the Issue on demo day was about versioning. 
can you explain it @mrvahedi68 ?

**Comment by michielbdejong** [comment]
Let's have a look at that bugfix, and try to estimate whether it is now trustworthy for all apps, or whether we fear that some other new app may have the same problem all over again.

@mrvahedi68 can you paste the link here to the upstream issue and bugfix you found?

**Comment by mrvahedi68** [comment]
I'm not sure about what happening at the demo. But when try to reproduce that error all functionalities works like charm. After read the change log of that library I found  that they have some bugfixes on 19 Aug for version [1.14.1](https://github.com/nextcloud/files_accesscontrol/releases/tag/v1.14.1) that seems is related to our problem. when I installed that version on nextcloud 24 (current version we are using) that bug not appears at all.

**Comment by mrvahedi68** [comment]
We are working with Nextcloud 24. The previous version for this version of Nextcloud is 1.14.0 and by installing this version the recent file blocks correctly. I think We have nothing else to check and can close the issue for now. @navid-dada
