### ISSUE TITLE
Wrap up milestone 5

### ISSUE THREAD

**Issue by michielbdejong** [pondersource/nextcloud-mfa-awareness#38]
I linked to the new app repo in https://github.com/pondersource/nextcloud-mfa-awareness and created #37.

Now I'm trying this out on GitPod and updating the readme instructions as I go along.

**Comment by michielbdejong** [comment]
I'm trying to compose a list of moving parts.
I think for globalsiteselector and user_saml our PRs have been merged now.
Then we have https://github.com/nextcloud/server/pull/35555
And https://github.com/pondersource/server/tree/feat/mfaverified-check (no PR opened yet?)
And https://github.com/pondersource/mfaverifiedzone
I'll see if I can get the gss flow working with those.

**Comment by michielbdejong** [comment]
i'll install both mfachecker and mfaverifiedzone.

**Comment by michielbdejong** [comment]
Latest status, after running composer install on the mounted apps:
the setup is apparently not completed for sunet-nc1, maybe the composer command exited unsuccessfully?
will continue debugging tomorrow.

**Comment by michielbdejong** [comment]
Next problem:
```
cd servers
./setup-saml.sh
[...]
chowning /var/www/html/config on sunet-nc2
Configuring user_saml on sunet-nc2
OCI runtime exec failed: exec failed: unable to start container process: exec: "./init-nc2-local-saml.sh": stat ./init-nc2-local-saml.sh: no such file or directory: unknown
```

**Comment by michielbdejong** [comment]
Ah, [this commit line](https://github.com/pondersource/nextcloud-mfa-awareness/commit/aefb5b646eb7678058102e088e8264d979f3c8ec#diff-af94859d4e3609b5d517c58ecc36bb33a557d31472650207ee4104ef50c6725bR52) was breaking everything!

**Comment by michielbdejong** [comment]
<img width="849" alt="Screenshot 2023-03-13 at 14 35 40" src="https://user-images.githubusercontent.com/408412/224721375-b75ab205-2862-436e-8295-b8a479d561d1.png">

**Comment by michielbdejong** [comment]
```
curl -k https://sunet-nc2/index.php/apps/user_saml/saml/metadata
<?xml version="1.0"?>
<md:EntityDescriptor xmlns:md="urn:oasis:names:tc:SAML:2.0:metadata"
                     validUntil="2023-03-15T13:53:31Z"
                     cacheDuration="PT604800S"
                     entityID="https://sunet-nc2/index.php/apps/user_saml/saml/metadata">
    <md:SPSSODescriptor AuthnRequestsSigned="false" WantAssertionsSigned="false" protocolSupportEnumeration="urn:oasis:names:tc:SAML:2.0:protocol">
        <md:NameIDFormat>urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified</md:NameIDFormat>
        <md:AssertionConsumerService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST"
                                     Location="https://sunet-nc2/index.php/apps/user_saml/saml/acs"
                                     index="1" />
        
    </md:SPSSODescriptor>

**Comment by michielbdejong** [comment]
"This version of Nextcloud is not compatible with PHP > 8"

**Comment by michielbdejong** [comment]
![Uploading Screenshot 2023-03-16 at 10.55.35.png…]()

**Comment by michielbdejong** [comment]
Ah, that one is fixed with a restart, progress!
![Screenshot 2023-03-16 at 11 08 36](https://user-images.githubusercontent.com/408412/225584677-1ffe860e-c4ef-4df0-92e0-f6a6671f2bd3.png)

**Comment by michielbdejong** [comment]
I renamed 'mfaresterictedzone__tag' to 'mfazone' and 'MFA Verified ... is not verified' to 'multi-factor authentication ... is not verified'

**Comment by michielbdejong** [comment]
You can "verify MFA" and be in an "MFA verified" state, but you can not "verify MFA verified" :)

**Comment by michielbdejong** [comment]
Hm, i'm not seeing my change yet in the UI:
![Screenshot 2023-03-16 at 11 46 10](https://user-images.githubusercontent.com/408412/225594064-934e9895-ec2c-4c19-b8d4-c6411f96a603.png)

**Comment by michielbdejong** [comment]
And I'll also publish it to the app store

**Comment by michielbdejong** [comment]
I'm back at metadata not found:
![Screenshot 2023-03-16 at 14 00 45](https://user-images.githubusercontent.com/408412/225624615-3aa8b628-119b-495a-8b77-170c48340d08.png)

**Comment by navid-shokri** [comment]
oh

I think this is because HTTP / HTTPS

It seems the SSP is not configured for HTTPS and it can just find the configuration by HTTP schema
