### ISSUE TITLE
Other ways of logging in

### ISSUE THREAD

**Issue by michielbdejong** [pondersource/nextcloud-mfa-awareness#4]
* [x] [TOTP](https://apps.nextcloud.com/apps/twofactor_totp) sets the `two_factor_auth_passed` key into the session
* [x] [WebAuthn](https://apps.nextcloud.com/apps/twofactor_webauthn) sets the `two_factor_auth_passed` key into the session
* [x] [gss slave](https://github.com/nextcloud/globalsiteselector) -> @mrvahedi68 is investigating

**Comment by navid-dada** [comment]
https://github.com/nextcloud/globalsiteselector#manualusermapping
We need to create a mapping configuration file to provide available user backends to inquire about the absent user in the master database.

**Comment by michielbdejong** [comment]
> create a mapping configuration file to provide available user backends

-> created issue 6 about that

**Comment by michielbdejong** [comment]
Using `setup-gss.sh` we can now confirm the SAML -> GSS leader -> GSS follower flow, and indeed we see there that by the time we're logged in to the follower and opening the mfachecker app, the SAML attribute is not in scope anymore. That is what we'll fix in #3.
