### ISSUE TITLE
Choose better app name?

### ISSUE THREAD

**Issue by michielbdejong** [pondersource/nextcloud-mfa-awareness#40]
The old app [mfachecker](https://github.com/pondersource/nextcloud-mfa-awareness/tree/main/mfachecker) only checked whether the current user was logged in with MFA, it did not create or enforce any MFA-only zones.

The new app [mfaverifiedzone](https://github.com/pondersource/mfaverifiedzone) does enable the user to create MFA-only zones, and also creates the workflow engine rule to enforce these. But the "zone" is a folder in a user's account, and MFA verification is something a visiting user may go through at the IDP. Therefore, a user may be MFA verified, but it doesn't make sense for a zone to  be MFA verified. So I'm thinking if we can give the app a more accurate name somehow

**Comment by michielbdejong** [comment]
Maybe just "MFA Zones" (slug: mfazones)?
@mickenordin what do you think / prefer?

**Comment by mickenordin** [comment]
We have been calling it "Secure Zones", but maybe MFA Zones is more correct and descriptive. I am fine with that.

**Comment by mrvahedi68** [comment]
Yes we can just use MFA zones. Currently new tab created with this name and we just need to change name of app.
