### ISSUE TITLE
module missing on CodeSpace.

### ISSUE THREAD

**Issue by navid-shokri** [pondersource/nextcloud-mfa-awareness#42]
when I run the `composer install `  inside ***server*** folder I am getting this error :warning: 

>Problem 1
    - Root composer.json requires PHP extension ext-zip * but it is missing from your system. Install or enable PHP's zip extension.
To enable extensions, verify that they are enabled in your .ini files:
    - /opt/php/8.0.27/ini/php.ini

@mrvahedi68

**Comment by mrvahedi68** [comment]
You can ignore this extension when running `composer install`. Read send error and at the end has a help for that.

**Comment by navid-shokri** [comment]
I solved the issue by using the command mentioned in the error message below.
> composer install --ignore-platform-req=ext-zip

But I think it is better that the trick be mentioned as a point inside the ReadMe doc
