### ISSUE TITLE
if-expression seems to be different between Check and mfachecker

### ISSUE THREAD

**Issue by michielbdejong** [pondersource/nextcloud-mfa-awareness#54]
Looks like https://github.com/nextcloud/server/pull/37195#issuecomment-1495431269 is right,
in https://github.com/nextcloud/server/pull/37195/files#diff-324119d2db6f3d5a6d7546558dd8011e16e04683d83c4d29d69ff5f250f353d1R62
we are only checking for SAML while https://github.com/pondersource/nextcloud-mfa-awareness/blob/7011a58/mfachecker/lib/Controller/PageController.php#L33-L53 checks for SAML, GSS, and local MFA.

**Comment by mrvahedi68** [comment]
Yes, I'll fix this.

**Comment by mrvahedi68** [comment]
Where `$user` variable fill? 
@michielbdejong @navid-dada 
https://github.com/pondersource/nextcloud-mfa-awareness/blob/7011a58/mfachecker/lib/Controller/PageController.php#LL52

**Comment by navid-shokri** [comment]
oops, you can fill it by using UserManager to retrieve the user using the given user Id.
