### ISSUE TITLE
Check if MFA Zone is accessible over other channels

### ISSUE THREAD

**Issue by michielbdejong** [pondersource/nextcloud-mfa-awareness#60]
We expect an MFA Zone to be accessible through the following channels:
* [x] the Nextcloud Files browser, if MFA verified as the owner of the file or folder
* [x] the Nextcloud Files browser, if MFA verified and a MFA-required file or folder was shared with you
* [x] the Nextcloud Files browser, if MFA verified and a MFA-required file or folder was shared with a local group you're a member of

But inaccessible through the following channels:
* [x] WebDAV
* [ ] mobile app
* [ ] desktop app
* [x] OCM share to a different Nextcloud server (even if you are MFA verified on that other server)
* [x] the Nextcloud Files browser, if logged in as the owner of the file or folder but without MFA
* [x] the Nextcloud Files browser, if logged in without MFA and a MFA-required file or folder was shared with you
* [x] the Nextcloud Files browser, if logged in without MFA and a MFA-required file or folder was shared with a local group you're a member of

Can we test all these scenarios manually, just to double-check again whether we truly understand how our solution works?

**Comment by mrvahedi68** [comment]
I can't find a way to login on desktop application.
Exposed port `80` from `sunet-nc2` and worked on browser but when I used it in desktop app faced with this error and I expected to open a web page to login and then back to app but nothing happens and only this error.

![Screen Shot 1402-04-02 at 00 34 48](https://github.com/pondersource/nextcloud-mfa-awareness/assets/34796044/22711e3c-b038-4495-bc9b-6bf6f4c26741)

any idea to test this app? @michielbdejong

**Comment by mrvahedi68** [comment]
I can't have access to protected files from other channels but could not check for desktop and android applications.
