### ISSUE TITLE
Recover lost code

### ISSUE THREAD

**Issue by michielbdejong** [pondersource/nextcloud-mfa-awareness#71]
The code that @mrvahedi68 wrote in July to get the app working in the way you can see in [the screenshots](https://github.com/pondersource/nextcloud-mfa-awareness/issues/69#issuecomment-1629752674) was unfortunately not committed, so we'll have to try to write that code again.

**Comment by mrvahedi68** [comment]
Done in: https://github.com/pondersource/mfazones/pull/10
