### ISSUE TITLE
Enabling the TOTP app breaks the sunet-nc2 server in several ways

### ISSUE THREAD

**Issue by michielbdejong** [pondersource/nextcloud-mfa-awareness#96]
https://github.com/pondersource/nextcloud-mfa-awareness/blob/sunet-custom-with-gss/servers/sunet-nextcloud/init-nc2-gss-follower.sh#L9

**Comment by MahdiBaghbani** [comment]
It seems this https://github.com/pondersource/nextcloud-mfa-awareness/issues/92 also fixes totp, The app now works without problem when totp is also enabled
